import sqlite3

conn = sqlite3.connect('test.db')
# teachers
conn.execute('''insert into tes(name, mother) 
                  values ('Мария Мариевна', 0);''')
conn.execute('''insert into tes(name, mother) 
                  values ('Ындына Ырвановна', 1);''')
conn.execute('''insert into tes(name, mother) 
                  values ('Паша Инаров', 1);''')
conn.execute('''insert into tes(name, mother) 
                  values ('Вита АК', 1);''')
conn.execute('''insert into tes(name, mother) 
                  values ('Реп-гангста', 1);''')
conn.execute('''insert into tes(name, mother) 
                  values ('Трудовик-Сэмэн', 1);''')
# lessons
conn.execute('''insert into subs(name, tes_id, love) 
                  values ('Литература', 1, 1);''')
conn.execute('''insert into subs(name, tes_id, love) 
                  values ('Физика', 2, 0);''')
conn.execute('''insert into subs(name, tes_id, love) 
                  values ('Уроки репа', 5, 1);''')
conn.execute('''insert into subs(name, tes_id, love) 
                  values ('Труд', 6, 1);''')
conn.execute('''insert into subs(name, tes_id, love) 
                  values ('Музыка', 4, 0);''')
conn.execute('''insert into subs(name, tes_id, love) 
                  values ('Farmologia', 3, 0);''')
# marks
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 1);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 1);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (4, 1);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 1);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 1);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 1);''')

conn.execute('''insert into marks(mark, sub_id)
                  values (5, 2);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 2);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 2);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (4, 2);''')

conn.execute('''insert into marks(mark, sub_id)
                  values (4, 3);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 3);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 3);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (4, 3);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 3);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (2, 3);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 3);''')

conn.execute('''insert into marks(mark, sub_id)
                  values (5, 4);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 4);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 4);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 4);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 4);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 4);''')

conn.execute('''insert into marks(mark, sub_id)
                  values (5, 5);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 5);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (4, 5);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (5, 5);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 5);''')
conn.execute('''insert into marks(mark, sub_id)
                  values (3, 5);''')

conn.commit()
conn.close()
