# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(534, 367)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_teacher = QtWidgets.QLineEdit(self.centralwidget)
        self.name_teacher.setEnabled(True)
        self.name_teacher.setGeometry(QtCore.QRect(20, 190, 211, 31))
        self.name_teacher.setText("")
        self.name_teacher.setClearButtonEnabled(False)
        self.name_teacher.setObjectName("name_teacher")
        self.from_teacher = QtWidgets.QPushButton(self.centralwidget)
        self.from_teacher.setGeometry(QtCore.QRect(20, 220, 211, 41))
        self.from_teacher.setObjectName("from_teacher")
        self.corr_data_teacher = QtWidgets.QPushButton(self.centralwidget)
        self.corr_data_teacher.setGeometry(QtCore.QRect(20, 260, 211, 41))
        self.corr_data_teacher.setObjectName("corr_data_teacher")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 240, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(255, 255, 0, 60)")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 211, 31))
        self.label_2.setObjectName("label_2")
        self.mark = QtWidgets.QLineEdit(self.centralwidget)
        self.mark.setEnabled(True)
        self.mark.setGeometry(QtCore.QRect(270, 150, 211, 31))
        self.mark.setText("")
        self.mark.setClearButtonEnabled(False)
        self.mark.setObjectName("mark")
        self.corr_mark = QtWidgets.QPushButton(self.centralwidget)
        self.corr_mark.setGeometry(QtCore.QRect(270, 180, 211, 41))
        self.corr_mark.setObjectName("corr_mark")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 120, 211, 31))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 31))
        self.label.setObjectName("label")
        self.name_lesson = QtWidgets.QLineEdit(self.centralwidget)
        self.name_lesson.setEnabled(True)
        self.name_lesson.setGeometry(QtCore.QRect(20, 40, 211, 31))
        self.name_lesson.setText("")
        self.name_lesson.setClearButtonEnabled(False)
        self.name_lesson.setObjectName("name_lesson")
        self.mean_marks_for_lesson = QtWidgets.QPushButton(self.centralwidget)
        self.mean_marks_for_lesson.setGeometry(QtCore.QRect(20, 70, 211, 41))
        self.mean_marks_for_lesson.setObjectName("mean_marks_for_lesson")
        self.corr_data_lesson = QtWidgets.QPushButton(self.centralwidget)
        self.corr_data_lesson.setGeometry(QtCore.QRect(20, 110, 211, 41))
        self.corr_data_lesson.setObjectName("corr_data_lesson")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(240, 40, 261, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.from_teacher.setText(_translate("MainWindow", "предмет"))
        self.corr_data_teacher.setText(_translate("MainWindow", "корректировать данные по\n"
"учителю"))
        self.label_2.setText(_translate("MainWindow", "name of teacher"))
        self.corr_mark.setText(_translate("MainWindow", "корректировать оценку"))
        self.label_3.setText(_translate("MainWindow", "id of mark"))
        self.label.setText(_translate("MainWindow", "name of lesson"))
        self.mean_marks_for_lesson.setText(_translate("MainWindow", "посчитать средний балл\n"
"по предметам"))
        self.corr_data_lesson.setText(_translate("MainWindow", "корректировать данные по\n"
"предмету"))
